services:
  n8n:
    image: ${N8N_IMAGE}
    environment:
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_HOST: ${PG_HOST}
      DB_POSTGRESDB_PORT: ${PG_PORT}
      DB_POSTGRESDB_USER: ${PG_USER}
      DB_POSTGRESDB_PASSWORD: ${PG_PASS}
      DB_POSTGRESDB_DATABASE: "n8n"
      DB_POSTGRESDB_SCHEMA: "public"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_SECURE_COOKIE: "false"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "true"
      N8N_GIT_NODE_DISABLE_BARE_REPOS: "true"
      N8N_PROTOCOL: ${N8N_SCHEME}
      N8N_PORT: 5678
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
    ports:
      - ${N8N_PORT}:5678
    restart: unless-stopped
