services:
  nocodb:
    image: ${NOCODB_IMAGE}
    environment:
      NC_DB: "pg://${PG_HOST}:${PG_PORT}?u=${PG_USER}&p=${PG_PASS}&d=nocodb"
      NC_AUTH_JWT_SECRET: ${SECRET_KEY}
      NC_MINIO_END_POINT: ${MINIO_HOST}
      NC_MINIO_PORT: ${MINIO_PORT}
      NC_MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      NC_MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      NC_MINIO_BUCKET: "nocodb-private"
      NC_MINIO_USE_SSL: "false"
      NC_PUBLIC_URL: ${NOCODB_SCHEME}://${NOCODB_DOMAIN}
    ports:
      - ${NOCODB_PORT}:8080
    restart: unless-stopped
